language: c
compiler:
  - gcc
  - clang   
env:
    global:
        - LIBUV_VER=1.11.0
before_install: 
    - wget https://github.com/libuv/libuv/archive/v$LIBUV_VER.tar.gz 
    - tar xvf v$LIBUV_VER.tar.gz 
    - pushd libuv-$LIBUV_VER
    - ./autogen.sh && ./configure --prefix=/usr && make
    - sudo make install
    - popd
    - pip install --user cpp-coveralls
script: cd build/debug && rm CMakeCache.txt && cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=1 ../.. && make 
sudo: required
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
